### ISSUE TITLE
Toggle doesnt seem to work anymore

### ISSUE THREAD

**Issue by maxkuhlmay** [paulbuechner/storybook-addon-data-theme-switcher#116]
Hey, first of all, thanks for your Plugin. It could make my live way easier.

I just installed it and configured it according to your readme. unfortunatly it doesnt set the data-theme on the html tag anymore :(

Neither on the global, nor on the tag inside the storybook iframe. 

Ive also tried to set up a new storybook project.

Maybe its because of the automatic dependendy updates?

**Comment by paulbuechner** [comment]
Hey!

Unfortunately, I'm unable to reproduce the issue as of the current version which is [`v3.0.0`](https://github.com/paulbuechner/storybook-addon-data-theme-switcher/releases/tag/v0.3.0)

 Please provide additional information so we can look into your issue. Please provide the full content of your `.storybook/preview.ts/js` and `.storybook/main.ts/js` files.

> Also please note, that the auto-update for deps is only local and not reflected in your installed package as long as I don't push a new version with bumped `peerDependencies` requirements.

**Comment by maxkuhlmay** [comment]
Good Morning, sorry for the late answer.

My files:

preview.ts
`
import { setCompodocJson } from '@storybook/addon-docs/angular';
import type { Preview } from '@storybook/angular';
import docJson from '../documentation.json';

import type { ThemeConfig } from 'storybook-addon-data-theme-switcher';

setCompodocJson(docJson);

const preview: Preview = {
	parameters: {
		actions: { argTypesRegex: '^on[A-Z].*' },
		controls: {
			matchers: {
				color: /(background|color)$/i,
				date: /Date$/i,
			},
		},
	},
};

export default preview;

export const globalTypes = {
	dataThemes: {
		defaultValue: {
			list: [
				{ name: 'Light', dataTheme: 'light', color: '#ffffff' },
				{ name: 'Dark', dataTheme: 'dark', color: '#000000' },
			],
		} satisfies ThemeConfig,
	},
};
`

main.ts

`import type { StorybookConfig } from '@storybook/angular';

const config: StorybookConfig = {
	stories: ['*.stories.@(js|jsx|mjs|ts|tsx)'],
	addons: [
		'@storybook/addon-links',
		'@storybook/addon-essentials',
		'@storybook/addon-interactions',
		'@storybook/addon-a11y',
		'@storybook/addon-storysource',
		'@storybook/addon-viewport',
		'@storybook/addon-docs',
		'@storybook/addon-console',
		'storybook-addon-data-theme-switcher',
	],
	framework: {
		name: '@storybook/angular',
		options: {},
	},
	core: {
		disableTelemetry: true,
	},
	staticDirs: ['assets'],
};
export default config;
`

Tested with:
- Edge Version 122.0.2365.63
- Firefox Dev Edition 124.0b6 (64-Bit)


Edit:
While writing the answer, i found out, that 
`controls: {
			matchers: {
				color: /(background|color)$/i,
				date: /Date$/i,
			},
		},
`

causes the problem.

You could update your readme with a hint

**Comment by paulbuechner** [comment]
Can you try:

```ts
const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
  globalTypes: {
    dataThemes: {
      defaultValue: {
        list: [
          { name: "Light", dataTheme: "light", color: "#ffffff" },
          { name: "Dark", dataTheme: "dark", color: "#000000" },
        ],
      } satisfies ThemeConfig,
    },
  },
} satisfies Preview;

export default preview;
```

**Comment by maxkuhlmay** [comment]
Hey, thanks for your answer.

Removing the following line actually worked for me:

```
		controls: {
			matchers: {
				color: /(background|color)$/i,
				date: /Date$/i,
			},
		},
```
Your way also worked for me :)

Thanks for your support.

You can close the issue
